version: '2'
services:
  Desktop-1:
    environment:
    - PASSWORD=cris
    - USER=cris
    cap_add:
    - SYS_PTRACE
    image: lordcris/nomachine
    stdin_open: true
    tty: true
    ports:
    - 4000:4000/tcp
